"use client";

// `@ant-design/icons` creates a React Context at module scope (for its
// ConfigProvider-driven theming), which breaks Server Components — Next.js's
// server React runtime doesn't provide `createContext` there. Every icon
// used anywhere in the app is re-exported from this single "use client"
// module instead, so Server Component pages can still render icons (they
// render as ordinary Client Component leaves) without importing
// `@ant-design/icons` directly themselves. Import icons from here, never
// from `@ant-design/icons` directly.
export {
  AccountBookOutlined,
  AimOutlined,
  AppstoreOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  BankOutlined,
  BarChartOutlined,
  BellOutlined,
  BlockOutlined,
  BookOutlined,
  BulbFilled,
  BulbOutlined,
  CalendarOutlined,
  CameraOutlined,
  CrownOutlined,
  CheckCircleOutlined,
  CheckOutlined,
  CheckSquareOutlined,
  ClockCircleOutlined,
  CloseCircleOutlined,
  CloseOutlined,
  CloudUploadOutlined,
  CompassOutlined,
  CopyOutlined,
  CreditCardOutlined,
  DashboardOutlined,
  DeleteOutlined,
  DownloadOutlined,
  DownOutlined,
  EditOutlined,
  ExclamationCircleOutlined,
  FallOutlined,
  FieldTimeOutlined,
  FileAddOutlined,
  FireOutlined,
  GiftOutlined,
  FileDoneOutlined,
  FileExcelOutlined,
  FileTextOutlined,
  FolderAddOutlined,
  GlobalOutlined,
  GoogleOutlined,
  ImportOutlined,
  InfoCircleOutlined,
  KeyOutlined,
  LoadingOutlined,
  LoginOutlined,
  LogoutOutlined,
  MailOutlined,
  MenuFoldOutlined,
  MenuOutlined,
  MenuUnfoldOutlined,
  MinusOutlined,
  MobileOutlined,
  PictureOutlined,
  PlayCircleOutlined,
  PlusCircleOutlined,
  PlusOutlined,
  QrcodeOutlined,
  QuestionCircleOutlined,
  ReadOutlined,
  ReloadOutlined,
  RightOutlined,
  RiseOutlined,
  RobotOutlined,
  RocketOutlined,
  ScanOutlined,
  SearchOutlined,
  SettingOutlined,
  ShareAltOutlined,
  SmileOutlined,
  SoundOutlined,
  StarOutlined,
  StopOutlined,
  SwapOutlined,
  TableOutlined,
  TagsOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  TrophyOutlined,
  UserAddOutlined,
  UserOutlined,
  WarningOutlined,
} from "@ant-design/icons";
